import { BsGit, BsMicrosoftTeams, BsTranslate } from 'react-icons/bs';
import { DiScrum } from 'react-icons/di';
import {
  FaAngular,
  FaBars,
  FaClock,
  FaCodeBranch,
  FaCss3Alt,
  FaDocker,
  FaEnvelope,
  FaExternalLinkAlt,
  FaGithub,
  FaGithubSquare,
  FaGlobeAmericas,
  FaGraduationCap,
  FaHtml5,
  FaLinkedin,
  FaPencilRuler,
  FaReact,
  FaSass,
  FaUser,
} from 'react-icons/fa';
import { FaArrowUpLong, FaXmark, FaCode } from 'react-icons/fa6';
import { GiCoffeeCup } from 'react-icons/gi';
import { IoIosArrowDown } from 'react-icons/io';
import {
  IoBriefcaseSharp,
  IoCalendarNumber,
  IoLogoFigma,
  IoLogoFirebase,
  IoLogoVue,
  IoRocketOutline
} from 'react-icons/io5';
import { PiCertificateFill } from 'react-icons/pi';
import { RiNodejsLine, RiTailwindCssFill } from 'react-icons/ri';
import {
  SiExpress,
  SiJest,
  SiJira,
  SiJavascript,
  SiMongodb,
  SiPostman,
  SiTypescript,
  SiVite,
  SiVitest,
} from 'react-icons/si';
import { VscVscode } from 'react-icons/vsc';

export const Icon = {
  angular: FaAngular,
  arrowDown: IoIosArrowDown,
  arrowUp: FaArrowUpLong,
  bars: FaBars,
  briefcase: IoBriefcaseSharp,
  calendar: IoCalendarNumber,
  certificate: PiCertificateFill,
  clock: FaClock,
  code: FaCode,
  codeBranch: FaCodeBranch,
  coffee: GiCoffeeCup,
  css: FaCss3Alt,
  docker: FaDocker,
  envelope: FaEnvelope,
  express: SiExpress,
  externalLink: FaExternalLinkAlt,
  figma: IoLogoFigma,
  firebase: IoLogoFirebase,
  git: BsGit,
  github: FaGithub,
  githubSquare: FaGithubSquare,
  globe: FaGlobeAmericas,
  graduation: FaGraduationCap,
  html: FaHtml5,
  javascript: SiJavascript,
  jest: SiJest,
  jira: SiJira,
  linkedin: FaLinkedin,
  mongodb: SiMongodb,
  node: RiNodejsLine,
  pencil: FaPencilRuler,
  postman: SiPostman,
  react: FaReact,
  rocket: IoRocketOutline,
  sass: FaSass,
  scrum: DiScrum,
  tailwind: RiTailwindCssFill,
  teams: BsMicrosoftTeams,
  translate: BsTranslate,
  typescript: SiTypescript,
  user: FaUser,
  vite: SiVite,
  vitest: SiVitest,
  vscode: VscVscode,
  vue: IoLogoVue,
  xmark: FaXmark,
};
